##############################################################################################
#  A python file to store the data in the list, which could be accessed by the main program. #
##############################################################################################


headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
}

# for trending news
trending_news_link = "https://www.ndtv.com/trends/trends"

# for weather update
weather_update_link = "https://weather.com/en-IN/weather/today/l/26.80,80.89?par=google"

# for ipl score update
cricket_update_link = "https://www.cricbuzz.com/"

# western songs chart
western_songs_link = "https://www.billboard.com/charts/billboard-global-200/"

# bollywood songs chart
bollywood_songs_link = (
    "https://www.jiosaavn.com/s/playlist/phulki_user/Weekly_Top_Songs/8MT-LQlP35c_"
)

# greet data
interactive_greet_response = [
    "What about yourself? 😃",
    "How are you doing? 😄",
    "How have you been? 😃",
    "How's it going with you? 😄",
    "How are things on your end? 😃",
    "How's everything with you? 😄",
]

interactive_news_response = [
    "Let's see the top trending news of the day 🧐",
    "Trending news of the day 📰",
    "Here's the top headlines of the day 🗞",
]

# collection of jokes
jokes = [
    "What will you call burj khalifa after 100 years? Bujurg khalifa",
    "Why cant Indians play football cause every time they take a corner they make a shop",
    "What do you call a lost indian women? Ms Singh",
    "What did the cookie say to the milk? Whats up duud",
    "What is the most endangered creature in India?. The baby girl",
    "What do you call a lazy kangaroo? A pouch potato.",
    'Why do we tell actors to "break a leg?" Because every play has a cast.',
    "What does a pig put on dry skin? Oinkment.",
    "What do you call it when a snowman throws a tantrum? A meltdown.",
    "My uncle named his dogs Timex and Rolex. They're his watch dogs.",
    "Did you hear about the guy whose left side was cut off? He's all right now.",
    "How do you open a banana? With a mon-key.",
    "Which is faster, hot or cold? Hot, because you can catch cold.",
    "What did one plate say to the other plate? Dinner's on me.",
    "Why do oranges wear sunscreen? So they don't peel.",
    "My wife told me to stop acting like a flamingo, so I had to put my foot down.",
    "What do you call a pig that does karate? A pork chop.",
    "Where does Batman go to the bathroom? The batroom.",
    "What do you call a pony with a sore throat? A little horse.",
    "What did the left eye say to the right eye? Between you and me, something smells.",
    "What did the mama tomato say to the baby tomato? Catch up!",
    "Why didn't the melons get married? Because they cantaloupe.",
    "What do you call a fake noodle? An impasta.",
    "How did the pig get to the hogspital? In a hambulance.",
    "I'm so good at sleeping I can do it with my eyes closed!",
    "Why does Humpty Dumpty love autumn? Because he had a great fall.",
    "What happens when a strawberry gets run over crossing the street? Traffic jam.",
    "Why did the cow jump over the moon? The farmer had cold hands.",
    'A termite walks into a bar and says, "So, is the bar tender here?"',
    "How does an octopus go into battle? Well-armed.",
    "What do you call a pudgy psychic? A four-chin teller.",
    "What do you get when you mix a cocker spaniel, a poodle, and a ghost? A cocker-poodle boo.",
    "How do celebrities stay cool? They have many fans.",
    'What does a pickle say when he wants to play cards? "Dill me in!"',
    "How much money does a pirate pay for corn? A buccaneer.",
    "Where do young trees go to learn? Elementree school.",
    "Why do bees have sticky hair? Because they use a honeycomb.",
    "How did the student feel when he learned about electricity? Totally shocked.",
    "What do you call a bee that can't make up its mind? A Maybe.",
    "Why was six afraid of seven? Because 7-8-9.",
    "If April showers bring May flowers, what do May flowers bring? Pilgrims.",
    "I tried to catch fog yesterday. Mist.",
    "What do you call a hippie's wife? Mississippi.",
    "Two peanuts were walking down the street. One was a-salted.",
    "How can you tell it's a dogwood tree? By the bark.",
    "What did the buffalo say when his kid went to college? Bison.",
    "What did the mayonnaise say when the refrigerator door was opened? Close the door, I'm dressing.",
    "What's the stinkiest planet? Poopiter.",
    "What did one wall say to the other? I'll meet you at the corner.",
    "Why don't sharks eat clowns? Because they taste funny.",
    'A horse walks into a bar. The bartender says, "Why the long face?"',
    "What did the pirate say when he turned 80? Aye matey.",
    "What's black and white and goes round and round? A penguin in the washing machine.",
    "How do you organize a space party? You planet.",
    "Why couldn't the bicycle stand up by itself? It was two tired.",
    "Did you hear the rumor about butter? Well, I'm not going to spread it.",
    "Why did the student eat his homework? Because his teacher told him it was a piece of cake.",
    "What did one hat say to the other? You wait here, I'll go on ahead.",
    "What do you call a dinosaur that crashes his car? Tyrannosaurus Wrecks.",
    "I couldn't figure out why the baseball kept getting larger. Then it hit me.",
    "What do you call a boomerang that won't come back? A stick.",
    "What did the full glass say to the empty glass? You look drunk.",
    "How do you stop a bull from charging? Cancel its credit card.",
    "Why don't we see elephants hiding in trees? Because they're really good at it.",
    "What's the difference between a hippo and a zippo? One's pretty heavy and the other's a little lighter.",
    "Did you hear the one about the roof? Never mind, it's over your head.",
    "I used to hate facial hair...but then it grew on me.",
    "A cheese factory exploded in France. Da brie was everywhere.",
    "What's a ninja's favorite type of shoes? Sneakers.",
    "What's the best smelling insect? A deodor-ant.",
    "What do you call a bear without any teeth? A gummy bear.",
    "Why was the coach yelling at the vending machine? He wanted his quarter back.",
    "Could a ... ... librarian be called a bookkeeper? ... referee be a game warden? ... dairyman be a cowboy? ... cabinetmaker be the president? Submitted by J. Lee",
    "There's a guy in town who walks around talking to himself using only figurative language. We call him the Village Idiom. Albert Sloan",
    "I can give you the cause of anaphylactic shock in a nutshell. Gary Delaney, comedian",
    "Q: What happened to the guy who sued over his missing luggage? A: He lost his case.",
    "Hal: How did you get hit on the head with a book? Sal: I only have my shelf to blame.",
    "Q. What did one blade of grass say to another about the lack of rain?A. I guess we'll just have to make dew.",
    "Trying to get online at my mother-in-law's, I scrolled through various Internet access names. One neighbors Wi-Fi really stood out:You Kids Get Off My LAN!",
    "Whats the difference between a poorly dressed man on a unicycle and a well-dressed man on a bicycle? Attire.",
    "Q: Why shouldn't you visit an expensive wig shop? A: It's too high a price 'toupee.'",
    "Q. What lies at the bottom of the ocean and twitches? A. A nervous wreck.",
    "Q. How much money does a pirate pay for corn? A. A buccaneer.",
    "Don't interrupt someone working intently on a puzzle. Chances are, you'll hear some crosswords.",
    "I'm a big fan of whiteboards. I find them quite re-markable.",
    "Q. Why was King Arthur's army too tired to fight? A. It had too many sleepless knights.",
    "Q. Which country's capital has the fastest-growing population? A. Ireland. Every day it's Dublin.",
    'I asked my French friend if she likes to play video games. She said, "Wii."',
    "Yesterday, a clown held the door open for me. It was such a nice jester!",
    "The machine at the coin factory just suddenly stopped working, with no explanation. It doesn't make any cents!",
    "I was going to make myself a belt made out of watches, but then I realized it would be a waist of time.",
    "Did you hear about the auto body shop that just opened? It comes highly wreck-a-mended.",
    "Q. What's the difference between a hippo and a Zippo? A. A hippo is really heavy, and a Zippo is a little lighter.",
    "All these sea monster jokes are just Kraken me up.",
    "Q. Why can't you run through a campground? A. You can only ran, because it's past tents.",
    "What do you call a thieving alligator? A Crookodile",
    "What do you call a bee that can't make up its mind? A Maybe",
    "What do you call a pig that does karate? Pork chop",
    "Q: What did the watermelon say to the cantaloupe? A: You're one in a melon",
    "Don't go bacon my heart. I couldn't if I fried.",
    "If you were a fruit, you'd be a fine-apple",
    "I love you from my head tomatoes",
    "Q: What do you get when two dinosaurs crash their cars? A: T-Rex",
    "Q: What job did the frog have at the hotel? A: Bellhop",
    "Q: What do you call a pig that does karate? A: Pork chop",
    "Q: What do you call an everyday potato? A: A commentator",
    "Q: How do you put a baby alien to sleep? A: You rocket",
    "Q: What do you call a thieving crocodile? A: A crookodile",
    "Q: What do you call a lazy kangaroo? A: A pouch potato",
    "Q: What did the volcano say to his wife? A: I lava you",
    "Q: What do you call and owl that does magic tricks? A: Hoodini",
    "Q: Why did the banana go to the doctor? A: It wasn't peeling well",
    "Q: What do you call a classy fish? A: Sofishticated",
    "Q: What do you call a bear with no teeth? A: Gummybear",
    "Are you a cheetah? No, you lion!",
    "Q: How do you organize a space party? A: You planet",
    "Becoming a vegetarian is a big missed steak.",
    "Q: What do you call and alligator in a vest? A: An investigator",
    "Q: What kind of shorts do clouds wear? A: Thunderwear",
    'Shout out to the people who ask what the opposite of "in" is',
    "I'm only friends with 25 letters of the alphabet. I don't know Y."
    "Q. What sound does a sleeping T-Rex make? A. A dino-snore.",
    'Two windmills are standing in a wind farm. One asks, "Whats your favorite kind of music?" The other says, "Im a big metal fan."',
    "Want to hear something terrible? Paper. See? I told you it was tear-able.",
    "A man sued an airline company after it lost his luggage. Sadly, he lost his case.",
    "Atoms are untrustworthy little critters. They make up everything!",
    "Why not go out on a limb? Isn't that where all the fruit is?",
    "My ex used to hit me with stringed instruments. If only I had known about her history of violins.",
    "Did you hear about the 2 silk worms in a race? It ended in a tie!",
    "Someone stole my toilet and the police have nothing to go on.",
    "Having sex in an elevator is wrong on so many levels.",
    "Last time I got caught stealing a calendar I got 12 months.",
    "Light travels faster than sound. That's why some people appear bright until you hear them speak",
    "I was wondering why the ball was getting bigger. Then it hit me",
    "I have a few jokes about unemployed people, but none of them work",
    '"I have a split personality," said Tom, being frank.',
    "I Renamed my iPod The Titanic, so when I plug it in, it says The Titanic is syncing.",
    "How do you make holy water? You boil the hell out of it",
    "Last night, I dreamed I was swimming in an ocean of orange soda. But it was just a Fanta-sea",
    "When life gives you melons, you're dyslexic",
    "Will glass coffins be a success? Remains to be seen",
    "I lost my job at the bank on my very first day. A woman asked me to check her balance, so I pushed her over",
    "It's hard to explain puns to kleptomaniacs because they always take things literally",
    "Two windmills are standing in a wind farm. One asks, What's your favorite kind of music? The other says, I'm a big metal fan.",
    "I can't believe I got fired from the calendar factory. All I did was take a day off",
    "Did you hear about the guy whose whole left side was cut off? He's all right now",
    "What's the difference between a hippo and a zippo? One is really heavy and the other is a little lighter",
    "The man who survived pepper spray and mustard gas is now a seasoned veteran",
    "My dad farted in an elevator, it was wrong on so many levels",
    "I went to buy some camouflage trousers yesterday but couldn't find any",
    "Hear about the new restaurant called Karma? There's no menu - you get what you deserve",
    "I tried to sue the airline for losing my luggage. I lost my case",
    "England doesn't have a kidney bank, but it does have a Liverpool",
    "A police officer just knocked on my door and told me my dogs are chasing people on bikes. That's ridiculous. My dogs don't even own bikes",
    "What do you call a bee that can't make up its mind? A maybe",
    "Jill broke her finger today, but on the other hand she was completely fine",
    "All chemists know that alcohol is always a solution",
    "When everything is coming your way, you're in the wrong lane",
    "The furniture store keeps calling me to come back. But all I wanted was one night stand",
    "A cross-eyed teacher couldn't control his pupils",
    "When the past, present, and future go camping they always argue. It's intense tense in tents",
    "She had a photographic memory but never developed it",
    "Let me tell you about my grandfather. He was a good man, a brave man. He had the heart of a lion, and a lifetime ban from the zoo",
    "What did the janitor say when he jumped out of the closet? SUPPLIES!",
    "My dad, unfortunately, passed away when we couldn't remember his blood type His last words to us were, Be positive!",
    "Is it ignorance or apathy that's destroying the world today? I don't know and don't really care",
    "A mean crook going downstairs = A condescending con, descending",
    "There was a kidnapping at school yesterday. Don't worry, though - he woke up",
    "I wasn't originally going to get a brain transplant, but then I changed my mind",
    "What do you call the wife of a hippie? A Mississippi",
    "Which country's capital has the fastest-growing population? Ireland. Every day its Dublin.",
    "How do you throw a space party? You planet",
    "What do you get when you mix alcohol and literature? Tequila mockingbird",
    "My ex-wife still misses me. But her aim is starting to improve",
    "What washes up on tiny beaches? Microwaves",
    "How does an attorney sleep? First, he lies on one side, then he lies on the other",
    "What are the strongest days of the week? Saturday and Sunday, the rest are weekdays",
    'Two fish are in a tank, one says to the other "how do you drive this thing?"',
    "I hate how funerals are always at 9 a.m. I'm not really a mourning person",
    "What's the difference between a poorly dressed man on a bicycle and a nicely dressed man on a tricycle? A tire",
    "What do you call an alligator in a vest? An investigator",
    "I was going to make a chemistry joke, but since I'm kinda late to the thread, the good ones argon",
    "The guy who invented the door knocker got a no-bell prize",
    "The other day I tried to make a chemistry joke, but got no reaction",
    "Need an ark? I Noah guy",
    "Sleeping comes so naturally to me, I could do it with my eyes closed",
    "I walked into my sister's room and tripped on a bra... It was a booby trap",
    "German sausage jokes are just the wurst",
    "How does Moses make coffee? Hebrews it",
    "Police were called to a daycare center where a three-year-old was resisting a rest",
    "What do you call the ghost of a chicken? A poultry-geist",
    "I used to be indecisive; now I'm not so sure",
    "I'm on a seafood diet. Every time I see food, I eat it",
    "He who laughs last thinks slowest",
    "I like European food so I decided to Russia over there because I was Hungary. After Czech'ing the menu I ordered Turkey. When I was Finnished I told the waiter 'It has been good but there is Norway I could eat another bite'",
    "What did the grape say when it got stepped on? Nothing - but it let out a little whine",
    "Why are frogs so happy? They eat whatever bugs them",
    "The machine at the coin factory just suddenly stopped working, with no explanation. It doesn't make any cents",
    "Somebody stole all my lamps I couldn't be more de-lighted!",
    "What do you call a super articulate dinosaur? A Thesaurus",
    "Why is the number six afraid of seven? Because seven ate nine",
    "What do you call a man with no arms and no legs stuffed in your mailbox? Bill",
    "Why aren't dogs good dancers? Because they have two left feet!",
    "What did one flag say to the other? Nothing, it just waved.",
    "I lost my mood ring, and I don't know how I'm feeling about that",
    "I'm not a doctor but I'm losing my patience",
    "How was Rome split in two? With a pair of Caesars",
    "I bought a boat because it was for sail",
    "Being vegetarian was a huge missed-steak",
    "What would you get if you'd put a lawyer in a suit? A lawsuit",
]

# collection of quotes
quotes = [
    "The journey of a thousand miles begins with one step ~ Lao Tzu",
    "That which does not kill us makes us stronger ~ Friedrich Nietzsche",
    "Life is what happens when you’re busy making other plans ~ John Lennon",
    "When the going gets tough, the tough get going ~ Joe Kennedy",
    "You must be the change you wish to see in the world ~ Mahatma Gandhi",
    "You only live once, but if you do it right, once is enough ~ Mae West",
    "Tough times never last but tough people do ~ Robert H ~  Schuller",
    "Get busy living or get busy dying ~ Stephen King",
    "Whether you think you can or you think you can’t, you’re right ~ Henry Ford",
    "Tis better to have loved and lost than to have never loved at all ~ Alrded Lord Tennyson",
    "A man is but what he knows ~ Sir Francis Bacon",
    "You miss 100 percent of the shots you never take ~ Wayne Gretzky",
    "If you’re going through hell, keep going ~ Winston Churchill",
    "Strive not to be a success, but rather to be of value ~ Albert Einstein",
    "Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do ~ Mark Twain",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people ~ Eleanor Roosevelt",
    "Those who dare to fail miserably can achieve greatly ~ John F ~  Kennedy",
    "The opposite of love is not hate; it’s indifference ~ Elie Wiesel",
    "Never let the fear of striking out keep you from playing the game ~ Babe Ruth",
    "Life is like a box of chocolates ~  You never know what you’re going to get ~ Forrest Gump",
    "He that falls in love with himself will have no rivals ~ Benjamin Franklin",
    "Life is ten percent what happens to you and ninety percent how you respond to it ~ Charles Swindoll",
    "Dream big and dare to fail ~ Norman Vaughan",
    "A great man is always willing to be little ~ Ralph Waldo Emerson",
    "That’s one small step for a man, one giant leap for mankind ~ Neil Armstrong",
    "Every man is guilty of all the good he did not do ~ Voltaire",
    "A successful man is one who can lay a firm foundation with the bricks others have thrown at him ~ David Brinkley",
    "In three words I can sum up everything I’ve learned about life: It goes on ~ Robert Frost",
    "If you judge people, you have no time to love them ~ Mother Teresa",
    "The future belongs to those who prepare for it today ~ Malcolm X",
    "Don’t be afraid to give up the good to go for the great ~ John D ~  Rockefeller",
    "The greatest glory in living lies not in never falling, but in rising every time we fall ~ Nelson Mandela",
    "When you reach the end of your rope, tie a knot in it and hang on ~ Franklin D ~  Roosevelt",
    "No one can make you feel inferior without your consent ~ Eleanor Roosevelt",
    "In the long run, the sharpest weapon of all is a kind and gentle spirit ~ Anne Frank",
    "Sing like no one’s listening, love like you’ve never been hurt, dance like nobody’s watching, and live like it’s heaven on earth ~ Mark Twain",
    "Do what you can, with what you have, where you are ~ Teddy Roosevelt",
    "People are just as happy as they make up their minds to be ~ Abraham Lincoln",
    "Every great dream begins with a dreamer ~  Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world ~ Harriet Tubman",
    "Success is not final, failure is not fatal: it is the courage to continue that counts ~ Winston Churchill",
    "Remember that the happiest people are not those getting more, but those giving more ~ H ~  Jackson Brown, Jr ~ ",
    "The only impossible journey is the one you never begin ~ Tony Robbins",
    "When I dare to be powerful to use my strength in the service of my vision, then it becomes less and less important whether I am afraid ~ Audre Lorde",
    "I have no special talent ~  I am only passionately curious ~ Albert Einstein",
    "The only person you are destined to become is the person you decide to be ~ Ralph Waldo Emerson",
    "May you live all the days of your life ~ Jonathan Swift",
    "We have nothing to fear but fear itself ~ Franklin D ~  Roosevelt",
    "Those who cannot remember the past are condemned to repeat it ~ George Santayana",
    "The only thing necessary for the triumph of evil is for good men to do nothing ~ Edmund Burke",
    "Insanity is doing the same thing over and over again and expecting different results ~ Albert Einstein",
    "Life would be tragic if it weren’t funny ~ Stephen Hawking",
    "It is never too late to be what you might have been ~ George Eliot",
    "The power of imagination makes us infinite ~ John Muir",
    "Everything you’ve ever wanted is on the other side of fear ~ George Addair",
    "We design our lives through the power of choices ~ Richard Bach",
    "Shoot for the moon ~  Even if you miss, you’ll land among the stars ~ Les Brown",
    "If you tell the truth, you don’t have to remember anything ~ Mark Twain",
    "Knowing yourself is the beginning of all wisdom ~ Aristotle",
    "We are what we repeatedly do; excellence, then, is not an act but a habit ~ Aristotle",
    "Life is not a problem to be solved, but a reality to be experienced ~ Sren Kierkegaard",
    "All that we see and seem is but a dream within a dream ~ Edgar Allen Poe",
    "The question isn’t who is going to let me; it’s who is going to stop me ~ Ayn Rand",
    "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present ~ Bil Keane",
    "What you do speaks so loudly that I cannot hear what you say ~ Ralph Waldo Emerson",
    "Those who make you believe absurdities can make you commit atrocities ~ Voltaire",
    "You can discover more about a person in an hour of play than in a year of conversation ~ Plato",
    "Once you’ve accepted your flaws, no one can use them against you ~ George R ~  R ~  Martin",
    "When we strive to become better than we are, everything around us becomes better too ~ Paolo Coelho",
    "Our greatest fear should not be of failure but of succeeding at things in life that don’t really matter ~ Francis Chan",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful ~ Joshua J ~  Marine",
    "You will face many defeats in life, but never let yourself be defeated ~ Maya Angelou",
    "Keep your face to the sunshine and you can never see the shadow ~ Helen Keller",
    "Always forgive your enemies; nothing annoys them so much ~ Oscar Wilde",
    "Power tends to corrupt, and absolute power corrupts absolutely ~ John Dalberg-Acton",
    "Do not go where the path may lead; go instead where there is no path and leave a trail ~ Ralph Waldo Emerson",
    "Those who cannot remember the past are condemned to repeat it ~ George Santayana",
    "Nothing is impossible, the word itself says, I’m possible! Audrey Hepburn",
    "Always remember that you are absolutely unique ~  Just like everyone else ~ Margaret Meade",
    "It is better to fail in originality than to succeed in imitation ~ Herman Melville",
    "A mind is like a parachute ~  It doesn’t work if it isn’t open ~ Frank Zappa",
    "I’m selfish, impatient and a little insecure ~  I make mistakes, I am out of control and at times hard to handle ~  But if you can’t handle me at my worst, then you sure as hell don’t deserve me at my best ~ Marilyn Monroe",
    "It is our choices, that show what we truly are, far more than our abilities ~ J ~ K ~  Rowling",
    "A lion doesn’t concern himself with the opinions of the sheep ~ Lionel Messi",
    "The way to get started is to quit talking and begin doing ~ Walt Disney",
    "Originality is nothing but judicious imitation ~ Voltaire",
    "A friend is someone who gives you total freedom to be yourself ~ Jim Morrison",
    "I alone cannot change the world, but I can cast a stone across the water to create many ripples ~ Mother Teresa",
    "It’s never too late to be who you might have been ~ George Eliot",
    "If you aren’t going all the way, why go at all?Joe Namath",
    "Science is what you know ~  Philosophy is what you don’t know ~ Bertrand Russell",
    "The successful warrior is the average man, with laser-like focus ~ Bruce Lee",
    "You know you’re in love when you can’t fall asleep because reality is finally better than your dreams ~ Dr ~  Seuss",
    "Ability is of little account without opportunity ~ Lucille Ball",
    "In order to write about life first you must live it ~ Ernest Hemingway",
    "The big lesson in life, baby, is never be scared of anyone or anything ~ Frank Sinatra",
    "We don’t stop playing because we grow old; we grow old because we stop playing ~ George Bernard Shaw",
    "If I have seen further than others, it is by standing upon the shoulders of giants ~ Isaac Newton",
    "Many of life’s failures are people who did not realize how close they were to success when they gave up ~ Thomas Edison\xa0",
    "When we strive to become better than we are, everything around us becomes better too ~ Paolo Coelho",
    "Holding onto anger is like drinking poison and expecting the other person to die ~ Buddha",
    "The further a society drifts from the truth, the more it will hate those that speak it ~ George Orwell",
    "All our dreams can come true if we have the courage to pursue them ~ Walt Disney",
    "You are never too old to set another goal or to dream a new dream ~ C ~ S ~  Lewis",
    "Life itself is the most wonderful fairy tale ~ Hans Christian Andersen",
    "It isn’t where you came from ~  It’s where you’re going that counts ~ Ella Fitzgerald",
    "Turn your wounds into wisdom ~ Oprah Winfrey",
    "Knowledge makes a man unfit to be a slave ~ Frederick Douglas",
    "Happiness is a direction, not a place ~ Sydney J ~  Harris",
    "Great geniuses have the shortest biographies ~ Ralph Waldo Emerson",
    "Try to be a rainbow in someone else’s cloud ~ Maya Angelou",
    "In the middle of difficulty lies opportunity ~ Albert Einstein",
    "Happiness depends upon ourselves ~ Aristotle",
    "Be yourself; everyone else is already taken ~ Oscar Wilde",
    "I am, therefore I think ~ Ayn Rand",
    "Whatever you do, do with all your might ~ Marcus Tullius Cicero",
    "All limitations are self-imposed ~ Oliver Wendel Holmes",
    "Time you enjoy wasting is not wasted time ~ Marthe Troly-Curtin",
    "Keep your friends close, but your enemies closer ~ Al Pacino, The Godfather Part II",
    "The time is always right to do what is right ~ Martin Luther King, Jr ~ ",
    "Well done is better than well said ~ Benjamin Franklin",
    "There is nothing impossible to him who will try ~ Alexander the Great",
    "This above all: to thine own self be true ~ William Shakespeare",
    "Actions speak louder than words ~ Abraham Lincoln",
    "The purpose of our lives is to be happy ~ Dalai Lama",
    "All that we are is the result of what we have thought ~ Buddha",
    "Arguing with a fool proves there are two ~ Doris Smith",
    "A penny saved is a penny earned ~ Benjamin Franklin",
    "All’s well that ends well ~ William Shakespeare",
    "The end doesn’t justify the means ~ Sergey Nechayev",
    "Look before you leap ~ Charlotte Bront",
    "Two heads are better than one ~ John Heywood",
    "Leave no stone unturned ~ Euripides",
    "The more things change, the more they remain the same ~ Jean-Baptiste Alphonse Karr",
    "Leave nothing for tomorrow which can be done today ~ Abraham Lincoln",
    "There’s a sucker born every minute ~ P ~ T ~  Barnum",
    "Everyone will be famous for 15 minutes ~ Andy Warhol",
    "An ounce of action is worth a ton of theory ~ Ralph Waldo Emerson",
    "A fool and his money are soon parted ~ Thomas Tusser",
    "He who angers you conquers you ~ Elizabeth Kenny",
    "A mind is a terrible thing to waste ~ Arthur Fletcher",
    "Two wrongs don’t make a right ~ Benjamin Rush",
    "You can’t make an omelet without breaking a few eggs ~ Francois de Charette",
    "Beggars can’t be choosers ~ John Heywood",
    "If it ain’t broke, don’t fix it ~ Bert Lance",
    "All good things must come to an end ~ Geoffrey Chaucer",
    "Beauty is in the eye of the beholder ~ Margaret Wolfe Hungerford",
    "Familiarity breeds contempt ~ Geoffrey Chaucer",
    "All things come to those who wait ~ Lady Mary Montgomerie Currie",
    "A chain is only as strong as its weakest link ~ Thomas Reid",
    "Honesty is the best policy ~ Edwin Sandys",
    "Don’t count your chickens before they hatch ~ Thomas Howell",
    "Even a stopped clock is right twice a day ~ Marie von Ebner-Eschenbach",
    "Great minds think alike ~ Carl Theodor von Unlanski",
]

# collection of quotes
poems = [
    "Hold fast to dreams, For if dreams die Life is a broken-winged bird That cannot fly.",
    "I will not play at tug o' war. I'd rather play at hug o' war, where everyone hugs Instead of tugs,",
    "If I can stop one heart from breaking, I shall not live in vain; If I can ease one life the aching, Or cool one pain,",
    "I made myself a snowball As perfect as could be. I thought I'd keep it as a pet And let it sleep with me.",
    "Nature's first green is gold, Her hardest hue to hold. Her early leaf's a flower; But only so an hour. ",
    "I been scarred and battered. My hopes the wind done scattered. Snow has friz me, Sun has baked me,",
    "Praise the spells and bless the charms, I found April in my arms. April golden, April cloudy, Gracious, cruel, tender, rowdy;",
    "Winter is the king of showmen, Turning tree stumps into snow men And houses into birthday cakes And spreading sugar over lakes.",
    "When I was One, I had just begun. When I was Two, I was nearly new.",
    "To keep your marriage brimming With love in the loving cup, Whenever you're wrong, admit it; Whenever you're right, shut up.",
    "Hold fast to dreams For if dreams die Life is a broken-winged bird That cannot fly.",
    "I will not play at tug o' war. I'd rather play at hug o' war, Where everyone hugs Instead of tugs,",
    "If I can stop one heart from breaking, I shall not live in vain;  If I can ease one life the aching, Or cool one pain,",
    "I made myself a snowball As perfect as could be. I thought I'd keep it as a pet And let it sleep with me.",
    "Nature's first green is gold,  Her hardest hue to hold.  Her early leaf's a flower; But only so an hour. ",
    "I been scarred and battered. My hopes the wind done scattered. Snow has friz me,  Sun has baked me,",
    "Praise the spells and bless the charms, I found April in my arms. April golden, April cloudy, Gracious, cruel, tender, rowdy;",
    "Winter is the king of showmen, Turning tree stumps into snow men And houses into birthday cakes And spreading sugar over lakes.",
    "When I was One, I had just begun. When I was Two, I was nearly new.",
    "To keep your marriage brimming With love in the loving cup, Whenever you're wrong, admit it; Whenever you're right, shut up.",
    "Some say the world will end in fire, Some say in ice. From what I've tasted of desire I hold with those who favor fire.",
    "When a friend calls to me from the road And slows his horse to a meaning walk, I don't stand still and look around On all the hills I haven't hoed,",
    "Listen to the MUSTN'TS, child, Listen to the DON'TS Listen to the SHOULDN'TS The IMPOSSIBLES, the WONT'S",
    "Boats sail on the rivers, And ships sail on the seas; But clouds that sail across the sky   Are prettier far than these.",
    "When I am dead and over me bright April  Shakes out her rain-drenched hair,Tho' you should lean above me broken-hearted,  I shall not care. ",
    "What are heavy? Sea-sand and sorrow; What are brief? Today and tomorrow; What are frail? Spring blossoms and youth; What are deep? The ocean and truth.",
    "I know what my heart is like Since your love died: It is like a hollow ledge Holding a little pool",
    "I hoped that he would love me, And he has kissed my mouth, But I am like a stricken bird  That cannot reach the south. ",
    "Underneath my outside face There's a face that none can see. A little less smiley, A little less sure,",
    "What happens to a dream deferred?  Does it dry up like a raisin in the sun?",
    "Some say the world will end in fire, Some say in ice. From what I’ve tasted of desire I hold with those who favor fire. But if it had to perish twice, I think I know enough of hate To say that for destruction ice Is also great And would suffice",
    "Nature’s first green is gold, Her hardest hue to hold. Her early leaf’s a flower; But only so an hour. Then leaf subsides to leaf. So Eden sank to grief, So dawn goes down to day. Nothing gold can stay.",
    " My candle burns at both ends; It will not last the night; But ah, my foes, and oh, my friends—It gives a lovely light!",
    "I think that I shall never see A poem lovely as a tree. A tree whose hungry mouth is prest Against the earth’s sweet flowing breast; A tree that looks at God all day , And lifts her leafy arms to pray A tree that may in Summer wear A nest of robins in her hair; Upon whose bosom snow has lain; Who intimately lives with rain. Poems are made by fools like me, But only God can make a tree.",
    "And then the day came, when the riskto remain tight in a bud was more painful than the risk it took to Blossom.",
    "The way a crow Shook down on meThe dust of snow From a hemlock tree Has given my heart A change of mood And saved some part Of a day I had rued.",
    "I'm nobody! Who are you? Are you nobody, too? Then there's a pair of us - don't tell! They'd banish us, you know. How dreary to be somebody! How public, like a frog To tell your name the livelong day To an admiring bog!",
]


# collection of facts
facts = [
    "The World's Oldest Hotel Has Been Operating Since 705 A.D.",
    "Yawning Cools Your Brain",
    "It Takes 68 Days to Swim the Full Length of the Mississippi River",
    "There Is a Boston Typewriter Orchestra",
    "Fleas Are Among the World's Best Jumpers",
    "An Apple Can Last up to 10 Months",
    'The Word "Tragedy" Comes from an Ancient Greek Word Meaning "Goat Song"',
    "The Creator of the Pringles Can is Buried in One",
    "The Wizard of Oz's Full Name is Oscar Zoroaster Phadrig Isaac Norman Henkel Emmannuel Ambroise Diggs",
    "Penguins Used to Be Six Feet Tall",
    "A Brewery in Canada Makes Beer Using Water from 20,000-Year-Old Icebergs",
    "The Slinky Was Created by Accident",
    "At Any Given Moment, There Are Approximately 2,000 Thunderstorms Happening on Earth",
    "Michelangelo Hated Painting the Sistine Chapel and Wrote a Poem About It",
    "A Million Earths Would Fit Inside the Sun",
    "The Letter Z Was Removed from the Alphabet for 200 Years",
    "The National Hot Dog and Sausage Council Ruled that Hot Dogs Aren't Sandwiches",
    "A Coffee Taster Had His Tongue Insured for 10 Million",
    "The Chills You Get When Listening to Music Are Caused by Your Brain Releasing Dopamine",
    "More People Tuned Into Prince Charles and Princess Diana's Wedding Than for the Friends, Cheers, Seinfeld, and M*A*S*H finales combined",
    'There are 10 Different Ways to Pronounce the Letters "Ough"',
    'The Word for Black Belt in Japanese Translates to "First Step"',
    "The World's Largest Pumpkin Weighs More Than a Sports Car",
    '"Natiform" Is a Term for Something That Looks Like a Bum',
    "Doctors Who Play Video Games More Than Three Hours a Week Make Fewer Operating Room Errors",
    "The Average American Woman Owns Seven Pairs of Jeans and Only Wears Four",
    "Dolly Parton Lost a Dolly Parton Lookalike Contest",
    "An NFL Referee Can Also Get a Super Bowl Ring",
    "The Lines on the Inside of Your Wrist Have a Name",
    "New York City Is Going to Get Bigger to Prepare for Climate Change",
    "A Sneeze Sounds Different Around the World",
    "A Belgian Pigeon Named Armando is Worth $1.4 Million",
    "Mars Exploration Has Its Own Scottish Tartan",
    "There Are More Than 60 Different Species of Eagles But Only Two Live in North America",
    "A Symbol Used in Place of a Curse Word Is Called a Grawlix",
    "Hairiness is Correlated With a Higher I.Q.",
    "Spam Mail Got Its Name from Monty Python",
    "Facebook's Blue Color Scheme is for Mark Zuckerberg's Benefit",
    "A Pianist Set a Guinness World Record by Performing at a Record-Breaking Height in Honor of her Mom",
    "Picasso Was a Suspect in the 1911 Mona Lisa Theft",
    "President Obama is a Two-Time Grammy Winner",
    "There's a Word for When You Can't Remember a Word",
    "The Record Lowest Temperature in the U.S. Was -80�F",
    "Male Monkeys Will Pay to Look at Female Monkeys",
    'A "Ghost Word" Is a Word that Became a Word by Error',
    "Legal Sea Food's Clam Chowder Has Been Served at Every Presidential Inauguration Since Reagan",
    'The Burnt Part of a Candlewick Is Called the "Snaste"',
    "Horseshoe Crabs Have Eyes All Over Their Bodies",
    "Lenny Kravitz and Al Roker Are Related",
    "Cheese May Prevent Nightmares",
    "French Poodles Aren't French",
    "Night Owls Tend to Be Smarter Than Early Birds",
    "Every Dutch Police Car Has a Teddy Bear in It",
    "There Is a Blonde Zebra in Africa",
    "It's Illegal to Sell Photos of the Eiffel Tower at Night",
    "There's a Patron Saint for Dentists",
    "Hawaiian Pizza is Canadian",
    'David Hasselhoff\'s Divorce Settlement Included Ownership of the Nickname "The Hoff"',
    "The World's Longest Fingernails Are More Than Two Feet Long",
    'Neanderthals Mass Produced Tools in a "Flintstone Factory" 60,000 Years Ago',
    "A Shrimp's Heart Is in Its Head",
    "Three Presidents Have Died on July 4th",
    "Scientists Believe They've Found Fossils from the Day the Asteroid Killed the Dinosaurs",
    "Barry Manilow Wrote the State Farm and Band-Aid Jingles",
    'The "ManhattAnt" Is a Species of Ant Unique to New York City',
    "Mr. Clean's Name Changes Around the Globe",
    "Goats Have Unique Accents",
    "The Earth Weighs About 13,170,000,000,000,000,000,000,000 Pounds",
    "The World's Oldest Tortoise is Twice as Old as Queen Elizabeth",
    "Charles Dickens Always Had His Bed Facing North",
    "One Region in Canada Has Lower Gravity Than Other Parts of the World",
    "350 Slices of Pizza Sell Every Second in America",
    "The World's Largest Waterfall Is Underwater in the Ocean",
    "It Only Appears as if Our Hair and Nails Keep Growing After We Die",
    "The World's Fist Hamburger Was Actually a Smushed Meatball",
    "Ernest Hemingway's Former Home is Overrun With Cats",
    "Tiny Pumpkin Toadlets Have a Glow-in-the-Dark Skeleton",
    '"Aviation English" Is the Language All Pilots Must Speak, No Matter What Nationality They Are',
    "Otters Hold Hands",
    "Early Americans Used Corn Cobs as Toilet Paper",
    "Ketchup Used to Be Considered a Medicine",
    "Polar Bears Don't Have White Skin or Fur",
    "Sudan Has Almost Twice as Many Pyramids as Egypt",
    "Barbie and Ken Have Full Names",
    "About 1 Out of Every 2,000 Babies Is Born With a Tooth",
    "T-Mobile Owns the Color Magenta",
    'The Only Words That Rhyme With "Purple" Are "Hirple" and "Curple"',
    "The Spanish National Anthem Has No Lyrics",
    "A Cat's Ear Has 32 Muscles",
    "The Vatican's ATMs Are in Latin",
    "There Are Frogs Smaller Than Your Fingernails",
    "Spotted Skunks Do Handstands",
    'A "Gowpen" Is What You Call It When You Cup Your Hands',
    "There's a Town in Western New York Populated by Psychics",
    "Asteroids Named After Tom Hanks and Meg Ryan Met Up Near Earth",
    "Female Lions Do More Hunting Than Males",
    "Dirty Dancing: Havana Nights Was Originally a Political Movie",
    "San Francisco is Mostly Water",
    "Early Horses Had 14 Toes Total, While Modern Horses Only Have Four",
    "Shakespeare Popularized the Name Jessica",
    "There is a Hot Pink Lake in Australia",
    "There Has Been One Documented Albino Penguin Chick",
    "Stephen King Boughtand Smashedthe Automobile That Nearly Killed Him",
    "The Empire State Building Has Its Own ZIP Code",
    "Chuck E. Cheese is a Nickname",
    "A Dog's Nose Is the Equivalent of a Human Fingerprint",
    '"She Sells Seashells by the Seashore" Was Likely Written About a 1800s Female Paleontologist Who Sold Dinosaur Bones',
    "The Color Orange Was Named After the Fruit",
    "The Largest Sand Castle Ever Can Be Seen from Space",
    "George Washington Was a Prolific Whiskey Maker",
    "New York's Washington Square Park is a Former Graveyard",
    "Jerry Springer Was Born in a London Subway Station During World War II",
    "There's an Opposite of Deja Vu",
    "Selfies Kill More People Than Sharks",
    "There Are Seven U.S. Towns Named After Santa",
    "There Are More Than a Million Ants For Every Person on Earth",
    "Dextrophobia Is the Fear of Having Objects to Your Right",
    "Andrew Jackson Owned a Lewd Parrot",
    "The Longest Underwater Kiss Lasted 20 Minutes and 11 Seconds",
    "Christmas With the Kranks Was Inspired by John Grisham",
    "Aquatic Snail Teeth Are the Hardest Natural Material",
    "Elephants Bury Their Dead",
    "Jane Austen Referenced Baseball 40 Years Before it Was Officially Invented",
    "Purdue University Created a Licking Machine to Finish Tootsie Pops",
    "A British Man Created an All-Lego House",
    "A Cat Served as the Mayor of an Alaska Town",
    "You Can See Four States from the Top of Chicago's Willis Tower",
    "Champagne Was Once Used as Shoe Polish",
    "Astronauts Celebrate Christmas in Space",
    "The Inventor of the Internet Regrets the URL Setup",
    "The Pacific Ocean Houses a Mysterious Singing Whale",
    'May 29 Is "Put a Pillow On Your Fridge Day"',
    "Sea Cucumbers Fight by Shooting Out Their Internal Organs Which Will Grow Back",
    "Dentistry Is One of the Oldest Professions, Dating Back to 7000 B.C.",
    'The Word "Computer" Was Used to Refer to a Person in the 1600s',
    'Darth Vader Never Says "Luke, I Am Your Father"',
    "The Very Middle of America is 2 Miles Northwest of Lebanon, Kansas on a Pig Farm",
    "Bulls Can't See Red",
    "Platypuses Moms Nurse Their Babies By Sweating Milk",
    "There's an Island in Japan Almost Entirely Populated by Bunnies",
    "British Military Tanks Are Equipped With a Tea-Making Area",
    "Daniel Radcliffe Was Allergic to Harry Potter's Glasses",
    "Most Wasabi Paste Isn't Real Wasabi",
    "Avocados Don't Ripen on Trees",
    "Olympic Gold Medals Are Only Partially Gold",
    "There's Only One Flying Mammal in the World",
    "You Need 10 Years of Cheesemaking Experience to Even Apply to Become a Master Cheesemaker",
    "You're Most Likely to Die on Your Birthday",
    "Your Dog Is as Smart as Your Toddler",
    "McDonald's Serves Spaghetti in the Philippines",
    "Google Was Nearly Called BackRub",
    "The Winner of the North American Wife Carrying Championship Gets Their Spouse's Weight in Beer",
    "Turkeys Sing",
    "Pizza Hut Used to Buy More Kale Than Anyone in the U.S.",
    "Divers Found the Remains of a 27,000-Year-Old Giant Sloth Stuck in a Sinkhole",
    'A Flock of Ravens Is Called an "Unkindness" or a "Conspiracy"',
    "In Michigan, You're Never Further than Six Miles from a Body of Water",
    "Cell Phones Are Illegal in One West Virginia Town",
    'A Grizzly-Polar Bear Hybrid Is Either Called a "Grolar Bear" or "Pizzly Bear"',
    "Oysters Can Change Sexes",
    '"Albert Einstein" Is an Anagram for "Ten Elite Brains"',
    "Waffle House Informs FEMA Decisions",
    "The Bigger Your Brain, the Longer You Yawn",
    "There's a Flower Shop in the White House",
    "The Pittsburgh Pirates Considered Building Their Stadium Over a River",
    "The First 3D Film Was Shown in 1922",
    "Ostriches Can Outrun Horses",
    "It's Impossible to Hum While Holding Your Nose",
    "Robert Downey, Jr. Used to Be Mr. Peanut's Voice",
    "Theres Is a Global Drone Racing League for Elite Drone Pilots",
    "Canada Has a Completely Indoor Town",
    "The Largest Collection of Comic Books Is Nearly 102,000 Strong",
    "Queen Elizabeth Was a Mechanic",
    "Owls Have Three Sets of Eyelids",
    "B�la Lugosi Was Buried in His Dracula Costume",
    "The World's Largest Teddy Bear Collection Numbers More Than 8,000",
    "Two of John Tyler's Grandsons Are Still Alive",
    "Cockroaches Can Survive Decapitation",
    "One Year on Uranus Is 84 Years on Earth",
    "In an Average Grocery Store, One-Quarter of All the Products Contain Ingredients That Come from Corn",
    "You Can Die From Laughter",
    "A Blue Whale's Heart is More Than Five Feet Long",
    'A 3,500-Year-Old Tablet May Contain the World\'s Oldest "Yo Mama" Joke',
    "Spiders Can Regrow Their Legs",
    "Steve Jobs' Last Words Were Awe-Inspired",
    'The Scientific Name for a "Brain Freeze" is Sphenopalatine Ganglioneuralgia',
    "Cows Get Excited When They Problem Solve",
    "Nearly One-Third of Alaska Lies Within the Arctic Circle",
    "Roses Can Grow Taller Than People",
    "No Two Tigers Have the Same Stripes",
    "Sharks Can Grow Thousands of Teeth",
    "Your Left Lung Is Smaller than Your Right Lung",
    'The Killer\'s "Mr. Brightside" Lyrics Repeat Because of Procrastination',
    "Early Pacemakers Had Wall Plugs",
    "Arizona's Meteor Crater Is Actually Named After a Post Office",
    "More Than 95 Percent of Passengers Involved in Plane Crashes Survive",
    "U.S. Paper Money Contains Hundreds of Species of Microorganisms",
    "New Hampshire Drinks the Most Alcohol of Any State",
    'Green Bay, Wisconsin, Is Known as the "Toilet Paper Capital of the World"',
    "Betty White Predates Sliced Bread",
]

# collection of memes
memes = [
    "https://i.chzbgr.com/full/9517757184/h1BE3058D/tanner-versaceminati-s-wrong-takes-long-drag-off-cigarette-my-sketchers-dont-light-up-anymore",
    "https://i.chzbgr.com/full/9545585152/h715F6971/packaged-goods-corona-lisa",
    "https://i.chzbgr.com/full/9545535744/h422123E1/months-after-friend-texted-him-fat-fk-every-day-va-sgag-com-he-saved-my-life-cant-thank-him-enough",
    "https://i.chzbgr.com/full/9549102080/h1B28A908/cat-gifbincom",
    "https://i.chzbgr.com/full/9516855040/h015C031D/person-help-mom-with-her-computer-and-dont-freak-out-on-her",
    "https://i.chzbgr.com/full/9097238528/h53420778/funny-memes-person-loading-afro-50",
    "https://i.chzbgr.com/full/9517451776/h8843E9DB/person-my-girl-wants-be-flash-halloween-thebedaz-zledunicorn",
    "https://i.chzbgr.com/full/9549103360/h011C89D4/furniture-after-doing-bare-minimum",
    "https://i.chzbgr.com/full/9545541632/hE4757361/point-10-mm-just-her-bic-compare-with-similar-items-new-2-1420-details-four-stars-november-30-2015",
    "https://i.chzbgr.com/full/9549119488/h7F2CD811/pay-these-taxes-are-unfair-lord-talk-lot-shit-someone-with-such-flammable-house-udanceswithshrews",
    "https://i.chzbgr.com/full/9545544704/h545C16DE/clothing-somebody-adds-another-plate-sink-while-im-washing-dishes",
    "https://i.chzbgr.com/full/9097243904/h0E044CD0/funny-memes-person-wtf-is-he-blow-drying-his-thoughts",
    "https://i.chzbgr.com/full/9516813568/hA7714C43/dog-omg-my-butt-is-awesome",
    "https://i.chzbgr.com/full/9545586176/hA95C6F09/00000000-agy-tollars-national-treanure-nc00000000-b2-uti-ng-00000000-100-1-tra-voltat-sto-214538-pe",
    "https://i.chzbgr.com/full/9545548032/hBD11C2DD/building-pirate-says-he-gets-kicked-nuts-memeinglessilfe-menar-ds-break-brunchcom",
    "https://i.chzbgr.com/full/9097239296/h1B226BDB/memes-person-come-in-here-and-say-that-again-ill-fuck-yr-shit-up-dry-boy-leg-havin-ass-land-bitch",
    "https://i.chzbgr.com/full/9545540608/h34C2582A/notcin-ratio-rehydrutesyouand-helpa-reless-likely-post-hela-men-feel-bere-leer-du-de-yt-yaad-lass",
    "https://i.chzbgr.com/full/9097238016/hAA3AC480/armed-men-in-my-home-me-lol-so-if-there-was-3-armed-men-thatd-be-crazy-like-mutants-reostermusiache",
    "https://i.chzbgr.com/full/9097239552/hAA74C532/funny-memes-when-you-die-of-anxiety-over-something-that-ended-up-fine-9261-st-olt-ah-fuk",
    "https://i.chzbgr.com/full/9545577216/h23B0715F/porn-link-co-worker-so-emailed-ten-other-co-workers-link-and-called-virus-improvise-adapt-overcome",
    "https://i.chzbgr.com/full/9516856064/hCE1C2B8E/person-do-thing-like-yea-one-large-pizza-delivery-please",
    "https://i.chzbgr.com/full/9097237504/hBAAE067B/funny-memes-window-blind-when-you-go-to-the-bathroom-to-look-at-memes-shitheadsteve-1-hr-p-o-o",
    "https://i.chzbgr.com/full/9097238272/h3EBA2E25/how-it-really-is-what-it-feels-like-a-convert-all-power-from-the-life-support-to-the-main-thrusters",
    "https://i.chzbgr.com/full/9097238784/h9DD21AFB/funny-memes-vegetable-when-youre-just-chillin-naked-with-bae-after-sex",
    "https://i.chzbgr.com/full/9517855232/hC8C21DFA/person-cut-hair-and-instantly-regret-memes-rush",
    "https://i.chzbgr.com/full/9545584640/h89B50B01/el-arroyo-aurtin-why-am-only-naked-person-at-this-gender-reveal-party",
    "https://i.chzbgr.com/full/9097237760/h457C38E8/eat-acid-and-try-and-join-in-on-a-sober-conversation-hmm-yes-the-floor-here-is-made-out-of-floor",
    "https://i.chzbgr.com/full/9545547520/h616F7688/tie-steve-harvey-0-steveharvey-stop-sending-this-shit-breakbrunchcom",
    "https://i.chzbgr.com/full/9097239040/h2D163B79/funny-memes-person-the-world-will-know-pro-pain",
    "https://i.chzbgr.com/full/9518884352/hB4E1F91D/but-also-horrifying-many-ways-didnt-originally-realize-1208-am-dec-10-2015-36k-retweets-82k-likes",
    "https://i.chzbgr.com/full/9097241344/hB75A8532/stock-phote-me-whats-his-fucking-problem-wife-try-singing-to-him-me-j-whats-your-fucking-problem",
    "https://i.chzbgr.com/full/9097240064/h11F9E2C9/he-just-grew-that-stupid-beard-2014-adult-swim-it-looks-like-2017-hell-be-here-forever-adult-swim",
    "https://i.chzbgr.com/full/9097241088/hC575DF94/funny-memes-animal-this-albino-squirrel-comes-to-our-door-and-rubs-its-nipples-and-just-stares-at-us",
    "https://i.chzbgr.com/full/9517024000/h569058D9/dog-short-and-no-one-takes-seriously-beware-dog-chillawack",
    "https://i.chzbgr.com/full/9097240832/hD9EF0AD3/on-animals-boss-why-shampoo-companies-do-it-all-the-time-guy-ya-but-we-make-dildos-guccigameboy",
    "https://i.chzbgr.com/full/9549104128/h462CE3CE/chilling-with-prehistoric-buddies-and-suddenly-massive-meteor-comes-crashing-down-guess-lll-die",
    "https://i.chzbgr.com/full/9097240320/hD5A23750/funny-memes-furniture-when-your-armour-doesnt-match-but-you-have-the-best-stats-wireless",
    "https://i.chzbgr.com/full/9097241600/h7B3B97CF/do-you-like-touch-my-balls-first-or-how-does-this-work-steven-im-your-dentist-ig-thofunnylntrovert",
    "https://i.chzbgr.com/full/9097241856/hEE3885E2/funny-memes-dog-when-i-get-the-attention-i-deserve",
    "https://i.chzbgr.com/full/9097243136/hF5D99D80/homie-arguing-about-something-and-the-google-search-confirms-your-intellectual-dominance-adult-swim",
    "https://i.chzbgr.com/full/9097244672/h8FC23710/funny-memes-dinosaur-when-you-leave-her-house-and-all-she-did-was-tease-you-for-6-hours",
    "https://i.chzbgr.com/full/9516853760/h0976D4F8/animal-netflix-asks-if-still-watching-and-see-reflection-black-screen",
    "https://i.chzbgr.com/full/9097242880/hDF10C79B/funny-memes-kitchenware-employees-must-applaud-the-planets-employees",
    "https://i.chzbgr.com/full/9097242112/h30AD0AAF/funny-memes-animal-when-you-get-home-from-work-and-you-can-finally-be-yourself-again",
    "https://i.chzbgr.com/full/9097242624/h61D5B807/funny-memes-animal-baby-stingrays-look-like-raviolis-stuffed-with-tiny-damned-souls",
    "https://i.chzbgr.com/full/9097243392/hE41C6B0C/funny-memes-man-when-you-baked-af-and-the-waitress-hits-you-with-hows-your-food-fuckersbelike",
    "https://i.chzbgr.com/full/9097243648/h2B3E7C63/funny-memes-bird-cat-cat-person-dog-dod-person-bird",
    "https://i.chzbgr.com/full/9097245952/hCC349863/here-who-thinko-ho-can-holp-you-yello-no-hels-a-scientist-batman-batmans-a-scientist-its-not-batman",
    "https://i.chzbgr.com/full/9097244928/hFF177D9A/memes-sunglasses-when-you-thought-you-had-1-in-your-bank-account-but-you-check-and-you-have-255",
    "https://i.chzbgr.com/full/9097245184/hE14AB75B/animal-take-me-down-to-the-bearadise-city-where-the-girls-are-bears-and-they-bare-bear-titties",
    "https://i.chzbgr.com/full/9549104384/h6963037B/person-fifth-mambo-c1380-ad-mary-lou-bega-rita-tina-erica-monica-sandra",
    "https://i.chzbgr.com/full/9545575936/h706FCBD8/animal-client-wants-combine-options-1-and-2-shorse-ig-theincumbentagency",
    "https://i.chzbgr.com/full/9097247232/hD75680E4/to-fear-is-fear-itself-biden-tugging-on-obamas-sleevel-obama-yes-joe-and-spiders-reverend-scott",
    "https://i.chzbgr.com/full/9097246208/hB55186B1/me-because-i-accidentally-sent-you-a-dick-pic-boss-stops-pouring-2-glasses-of-wine-accidentally",
    "https://i.chzbgr.com/full/9545543424/hCDEEB7B8/tie-parents-preparing-new-school-year-have-no-idea-s-going-on",
    "https://i.chzbgr.com/full/9097246720/hEEE4A56C/funny-memes-no-one-cared-whol-was-until-0-put-on-the-mask",
    "https://i.chzbgr.com/full/9097245696/h2F2A344D/ignoring-their-out-of-control-kid-guess-if-you-want-children-beaten-you-have-to-do-ityourself",
    "https://i.chzbgr.com/full/9097246464/h4D602FFE/funny-memes-person-belle-and-beasts-child",
    "https://i.chzbgr.com/full/9097248512/h6F0D3E8F/memes-animal-when-u-walk-in-ur-birds-room-without-knocking-shitheadsteve-mating-noises-8888bb-addo",
    "https://i.chzbgr.com/full/9517846272/h06A94C20/person-hollywood-logic-bad-guys-dont-deserve-nose",
    "https://i.chzbgr.com/full/9097249280/h6F339383/funny-memes-man-agent-are-you-carrying-any-explosives-man-just-this-bomb-ass-dick",
    "https://i.chzbgr.com/full/9097249792/h775DB745/funny-memes-woman-when-your-boss-walks-by-and-u-gotta-pretend-to-be-working-73a-unitel",
    "https://i.chzbgr.com/full/9097242368/hA48E121E/annoys-u-but-u-feel-like-youve-already-talked-about-it-too-much-so-u-just-hold-it-in-let-it-annoy-u",
    "https://i.chzbgr.com/full/9097244160/hDE0C4814/alert-alery-weather-authority-fox-29-west-chester-pa-chester-county-1240-34-cexperieng-posto",
    "https://i.chzbgr.com/full/9517450496/hA6349D9E/person-someone-sum-up-america-one-picture",
    "https://i.chzbgr.com/full/9516874496/h2A7EA0F3/dog-s-kitten-hairband",
    "https://i.chzbgr.com/full/9097250048/h8FB87A2C/funny-memes-person-without-my-voice-how-can-i-hd-cinemagic-boobs-hd-cinemagia",
    "https://i.chzbgr.com/full/9516610560/h4FA3F6B0/person-presenting-class-and-someone-says-can-speak-up-cant-hear",
    "https://i.chzbgr.com/full/9517015296/hD58A8115/and-he-didnt-know-say-chicken-so-he-grabbed-an-egg-and-went-cashier-and-asked-where-mother",
    "https://i.chzbgr.com/full/9545547776/h5F272999/have-cute-nicknames-eachother-3-thunde-dungean-big-fucking-weird-looking-walrus-fuck-breakbrunchcom",
    "https://i.chzbgr.com/full/9517448960/hA2875E4F/person-friends-are-arguing-about-whether-answer-44-or-45-and-answer-south-africa",
    "https://i.chzbgr.com/full/9517450240/hA857ECBB/person-dont-get-why-lm-not-loosing-weight",
    "https://i.chzbgr.com/full/9549107712/hC6AFDCA1/person-have-conquer-mongolia-but-cat-needs-walk-first",
    "https://i.chzbgr.com/full/9517475072/hBC6BCCE3/doll-trying-walk-drunk-dont-worry-got-this",
    "https://i.chzbgr.com/full/9517844992/h3BD33557/person-real-name-isnt-mom",
    "https://i.chzbgr.com/full/9516820736/h6B75BD5B/truck-crashed-carrying-ramen-noodles-estimated-company-loss-3800",
    "https://i.chzbgr.com/full/9517055744/h5038E181/alien-oh-chill-anyway-why-didnt-think-leader-alien-no-no-why-1031-pm-25-may-2015-t7-12048-17773",
    "https://i.chzbgr.com/full/9516847360/h21D69CF2/cake-eggs-are-fantastic-fitness-diet-dont-like-taste-add-cocoa-butterflour-bake-30-minutes",
    "https://i.chzbgr.com/full/9545583872/hC6C37803/shoe-had-sudden-burst-rain",
    "https://i.chzbgr.com/full/9516876800/hE62B9DB2/cat-person-u-should-try-make-more-friends-chase",
    "https://i.chzbgr.com/full/9517048320/hD64F3DC6/kool-aid-man-carry-smaller-pitcher-kool-aid-sir-m-is-his-piss-1115-am-12-mar-2015-6-17-5577-11361",
    "https://i.chzbgr.com/full/9516872448/hC12F0CAC/person-my-husband-explaining-obesity-chart-at-vets-office-our-cat-lenny",
    "https://i.chzbgr.com/full/9516873984/h8801CD36/shoe-trying-be-sexy",
    "https://i.chzbgr.com/full/9516870400/hBA1BB8E2/dog-almost-forgot-my-briefcase-contains-important-lab-results",
    "https://i.chzbgr.com/full/9516848640/h93E6D9DF/dog-dont-know-kind-dog-this-is-but-would-definitely-ride-into-battle",
    "https://i.chzbgr.com/full/9549103616/h18F3744E/book-but-kids-and-husband-all-want-tell-every-detail-everything-theyve-ever-done-since-birth",
    "https://i.chzbgr.com/full/9516871680/hEB6EDDBD/dog-u-sleep-on-couch-and-someone-wakes-u-up-and-tells-u-get-ur-bed",
    "https://i.chzbgr.com/full/9549106432/h9D5A9E05/person-have-an-excellent-work-environment-work-environment",
    "https://i.chzbgr.com/thumb400/6032389/h6B341E70/plane-lands-is-whites-lazy-eye-meme-about-checking-a-girls-boobs-while-she-is-showing-you-something",
    "https://i.chzbgr.com/thumb400/16721669/h7791C89D/funny-random-memes-dank-memes-humor",
    "https://i.chzbgr.com/thumb400/16717573/h215A62D2/bridezilla-horrible-weddings-cringe-disaster-reddit-funny-memes-groom-marriage-relationships-fail",
    "https://i.chzbgr.com/thumb400/16716805/h2DFCF6FF/dragons-memes-dnd-memes-tabletop-memes-gaming-memes-memes-funny-memes-lol-dank-memes-dungeon-master",
    "https://i.chzbgr.com/thumb400/16705797/h310760F4/dank-memes-dumb-memes-meme-dump-memes-funny-good-memes-relatable-memes-funny-tweets-animal-memes",
    "https://i.chzbgr.com/thumb400/16719109/hDCB1BD22/twitter-thread-funny-thread-embarrassing-funny-twitter-memes-funny-tweets-relatable-fail-facepalm",
    "https://i.chzbgr.com/thumb400/15976709/hF41E8C26/funny-memes-cat-memes-animal-memes-wholesome-memes-cats-memes-funny-lol",
    "https://i.chzbgr.com/thumb400/15978245/h095B2A1A/wholesome-memes-cute-aww-animal-memes-cat-memes-dog-memes-animals-heartwarming-funny-memes",
    "https://i.chzbgr.com/thumb400/15976709/hF41E8C26/funny-memes-cat-memes-animal-memes-wholesome-memes-cats-memes-funny-lol",
    "https://i.chzbgr.com/thumb400/16705797/h310760F4/dank-memes-dumb-memes-meme-dump-memes-funny-good-memes-relatable-memes-funny-tweets-animal-memes",
    "https://i.chzbgr.com/thumb400/15978501/hDA656EE1/osha-funny-funny-pics-wtf-life-hacks-stupid-people-construction-osha-violation-memes-fail-diy",
    "https://i.chzbgr.com/thumb400/16713221/h63FDE396/memes-funny-funny-memes-dank-memes-random-random-memes-dumb-memes-meme-dump-relatable-memes-lol-lmao",
    "https://i.chzbgr.com/thumb400/16717061/hFC01F73D/funny-cat-memes",
    'https://s3.scoopwhoop.com/anj2/5fbb819960c0603f5625e604/222f1044-32a8-4e69-ae15-d1070d954086.jpg"/>',
    'https://s3.scoopwhoop.com/anj2/5fbb801160c0603f5625e5e9/cecd78fd-83cf-434d-82d6-7393f80d91f0.jpg"/>',
    'https://s4.scoopwhoop.com/anj2/5f8961a760c06057c7630cc7/c641fa09-4514-4418-b5da-f35f9d8aaf15.jpg"/>',
    'https://s4.scoopwhoop.com/anj2/5f895d2a18ac812db947ac80/7464ef4b-c6f2-4f88-b0ac-8d964852de05.jpg"/>',
    'https://s4.scoopwhoop.com/anj2/5f67c62e60c060624d5a29f5/76332a3e-fc55-4fd9-a456-004a4a9045d2.jpg"/>',
    'https://s3.scoopwhoop.com/anj2/5f67c58660c060624d5a29eb/fbaa2b20-9611-4a22-85a7-388044a76b48.jpg"/>',
    'https://s4.scoopwhoop.com/anj2/5f67c49860c060624d5a29e6/63f700f1-c96e-4e2e-bfc5-16e80558d71e.jpg"/>',
    'https://s3.scoopwhoop.com/anj2/5f52133f18ac814f1f40419b/56989572-efcc-46f2-837d-9ac498c4c0d6.jpg"/>',
    'https://s3.scoopwhoop.com/anj2/5f520f0660c0604ebcb125c3/6e7a9a21-6602-4756-855f-0ed546bff687.jpg"/>',
]
